name: almhnaken
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencies for our features
  provider: ^6.1.1 # لإدارة الحالة
  shared_preferences: ^2.2.2 # للتخزين المحلي
  video_player: ^2.8.1
  # For the new icons (if you choose to use them)
  material_design_icons_flutter: ^5.0.6595 # لإضافة أيقونات بديلة ومحسّنة
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  url_launcher: ^6.1.10
  string_similarity: ^2.0.0
  font_awesome_flutter: ^10.10.0
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  animations: ^2.0.11
  google_mobile_ads: ^6.0.0
  firebase_storage: ^12.3.2
  youtube_explode_dart: ^2.1.0
  cached_network_image: ^3.3.1
  firebase_messaging: ^15.2.10
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your application, add an assets section here.
  assets:
    - videos/
    - iconUser/
    - strike/
    - image/
     # مسار الصور الذي قمت بتحديده

  # To add custom fonts to your application, add a fonts section here.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic